---
version: '3'

silent: true

tasks:
  default:
    desc: find out a bit more about myself
    summary: |
      query github and aws for my current identity
    deps:
      - check-aws-id
      - check-github-id

  selftest:

  check-github-id:
    desc: confirm SSH credentials are in place and show GitHub Identity
    cmds:
      - which ssh && ssh -V | head -1
      - ssh -T git@github.com 2>&1 || true

  check-aws-id:
    desc: confirm AWS credentials are available and show identity
    cmds:
      - which aws && aws --version | head -1
      - aws sts get-caller-identity --output table
